version: '3.7'

services:
  app:
    restart: unless-stopped
    build:
      context: '.'
      args:
        CONFLUENCE_VERSION: '6.14.2'
    ports:
      - '0.0.0.0:${CONFLUENCE_PORT:-8090}:8090'
    volumes:
      - './data/confluence:/var/confluence'

  db:
    restart: unless-stopped
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'confluence'
      POSTGRES_PASSWORD: 'confluence'
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
