version: '3.7'

services:
  roundcube:
    restart: unless-stopped
    image: 'roundcube/roundcubemail:${ROUNDCUBE_VERSION:-latest}'
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: '${IMAP_SERVER:-ssl://mail.example.com}'
      ROUNDCUBEMAIL_DEFAULT_PORT: ${IMAP_PORT:-993}
      ROUNDCUBEMAIL_SMTP_SERVER: '${SMTP_SERVER:-tls://mail.example.com}'
      ROUNDCUBEMAIL_SMTP_PORT: ${SMTP_PORT:-587}
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: '50M'
      ROUNDCUBEMAIL_DB_TYPE: 'mysql'
      ROUNDCUBEMAIL_DB_HOST: 'mysql'
      ROUNDCUBEMAIL_DB_USER: '${MYSQL_USER:-roundcube}'
      ROUNDCUBEMAIL_DB_PASSWORD: '${MYSQL_PASSWORD:-roundcube}'
      ROUNDCUBEMAIL_DB_NAME: 'roundcube'
    ports:
      - '127.0.0.1:${ROUNDCUBE_PORT:-8080}:80'

  mysql:
    image: 'mariadb:${MARIADB_VERSION:-latest}'
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'roundcube'
      MYSQL_USER: '${MYSQL_USER:-roundcube}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-roundcube}'
    volumes:
      - 'mysql-data:/var/lib/mysql:rw'

volumes:
  mysql-data:
