version: '3.7'

services:
  grafana:
    image: 'grafana/grafana:${GRAFANA_VERSION:-latest}'
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: '${GRAFANA_URL:-http://localhost:3000}'
      GF_SECURITY_ADMIN_PASSWORD: '${GRAFANA_PASSWORD:-secret}'
    volumes:
      - 'grafana-data:/var/lib/grafana:rw'
    ports:
      - '0.0.0.0:${GRAFANA_PORT:-3000}:3000'

volumes:
  grafana-data:
