version: '3.7'

services:
  wordpress:
    image: 'wordpress:${WORDPRESS_VERSION:-latest}'
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: 'mysql'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: '${MYSQL_USER:-wordpress}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD:-wordpress}'
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        ini_set('upload_max_filesize', '64M');
        ini_set('post_max_size', '128M');
        ini_set('memory_limit', '256M');
        ini_set('max_execution_time', 300);
        ini_set('max_input_time', 300);
        define('WP_HOME', '${WORDPRESS_URL:-http://localhost:8080}');
        define('WP_SITEURL', '${WORDPRESS_URL:-http://localhost:8080}');
    ports:
      - '127.0.0.1:${WORDPRESS_PORT:-8080}:80'
    volumes:
      - 'wordpress-plugins:/var/www/html/wp-content/plugins:rw'
      - 'wordpress-themes:/var/www/html/wp-content/themes:rw'
      - 'wordpress-uploads:/var/www/html/wp-content/uploads:rw'

  mysql:
    image: 'mariadb:${MARIADB_VERSION:-latest}'
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: '${MYSQL_USER:-wordpress}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-wordpress}'
    volumes:
      - 'mysql-data:/var/lib/mysql:rw'

volumes:
  wordpress-plugins:
  wordpress-themes:
  wordpress-uploads:
  mysql-data:

