version: '3.7'

services:
  mongo:
    image: 'mongo:3'
    restart: unless-stopped
    volumes:
      - 'mongo-data:/data/db:rw'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.6.2'
    restart: unless-stopped
    environment:
      http.host: '0.0.0.0'
      transport.host: 'elasticsearch'
      network.host: '0.0.0.0'
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    volumes:
      - 'es-data:/usr/share/elasticsearch/data:rw'
    ulimits:
      memlock:
        soft: -1
        hard: -1

  graylog:
    image: 'graylog/graylog:${GRAYLOG_VERSION:-3.0}'
    restart: unless-stopped
    environment:
      GRAYLOG_PASSWORD_SECRET: 'somepasswordpepper'
      GRAYLOG_ROOT_PASSWORD_SHA2: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918'
      GRAYLOG_HTTP_EXTERNAL_URI: '${GRAYLOG_URL:-/}'
      GRAYLOG_ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    volumes:
      - 'graylog-data:/usr/share/graylog/data:rw'
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:1514:1514'
      - '0.0.0.0:1514:1514/udp'
      - '0.0.0.0:12201:12201'
      - '0.0.0.0:12201:12201/udp'

volumes:
  graylog-data:
  mongo-data:
  es-data:
