version: '3.7'

services:
  jira:
    restart: unless-stopped
    build:
      context: '.'
      args:
        JIRA_VERSION: '${JIRA_VERSION:-8.0.2}'
    environment:
      JIRA_MAX_MEM: '${JIRA_MAX_MEM:-1024}'
      JIRA_URL: '${JIRA_URL:-}'
    ports:
      - '127.0.0.1:${JIRA_PORT:-8080}:8080'
    volumes:
      - 'jira-data:/var/jira:rw'

  postgres:
    restart: unless-stopped
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-jira}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-jira}'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data:rw'

volumes:
  jira-data:
  postgres-data:
