version: '3.7'

services:
  app:
    restart: unless-stopped
    build:
      context: '.'
      args:
        JIRA_VERSION: '8.0.2'
    ports:
      - '0.0.0.0:${JIRA_PORT:-8080}:8080'
    volumes:
      - './data/jira:/var/jira'

  db:
    restart: unless-stopped
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'jira'
      POSTGRES_PASSWORD: 'jira'
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
