version: '3.7'

services:
  unifi:
    restart: unless-stopped
    build:
      context: '.'
      args:
        UNIFI_VERSION: '${UNIFI_VERSION:-5.10.21}'
    ports:
      - '0.0.0.0:8080:8080'
      - '0.0.0.0:8081:8081'
      - '0.0.0.0:8443:8443'
      - '0.0.0.0:8843:8843'
      - '0.0.0.0:8880:8880'
      - '0.0.0.0:6789:6789'
      - '0.0.0.0:3478:3478/udp'
      - '0.0.0.0:10001:10001/udp'
    volumes:
      - 'unifi-data:/usr/lib/unifi/data:rw'

volumes:
  unifi-data:
