version: '3.7'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${GITLAB_URL:-http://localhost:8080}"
        gitlab_rails['gitlab_signup_enabled'] = false
        nginx['enable'] = true
        nginx['client_max_body_size'] = '1g'
        nginx['redirect_http_to_https'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT:-2222}
    ports:
      - '127.0.0.1:${GITLAB_PORT:-8080}:80'
      - '127.0.0.1:${GITLAB_REGISTRY_PORT:-5050}:5050'
      - '127.0.0.1:${GITLAB_SSH_PORT:-2222}:22'
    volumes:
      - 'gitlab_config:/etc/gitlab:rw'
      - 'gitlab_data:/var/opt/gitlab:rw'

volumes:
  gitlab_config:
  gitlab_data:
